-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg4QCQcuiYmbwq4lb4
ZkNkjzDmZ5GKTYJlY3XrsEUg1g+gCgYIKoZIzj0DAQehRANCAATMtE1QvcPEAB8n
PtWb0XTIhoYt7MoyfHAPCih5Zl1RZp9fHOyYDLNiRACeIIFg8KRz0TMLEPHIX0v1
pHZwCgdW
-----END PRIVATE KEY-----